ALTER TABLE FEED_POSTS MODIFY (
  NOME_USUARIO NVARCHAR2(160),
  TIPO_USUARIO NVARCHAR2(20),
  MENSAGEM NVARCHAR2(1000)
);

ALTER TABLE FEED_COMENTARIOS MODIFY (
  NOME_USUARIO NVARCHAR2(160),
  COMENTARIO NVARCHAR2(500)
);
