CREATE TABLE FEED_POSTS (
  ID NUMBER PRIMARY KEY,
  EMPRESA_ID NUMBER NOT NULL,
  USUARIO_ID NUMBER NOT NULL,
  NOME_USUARIO NVARCHAR2(160) NOT NULL,
  TIPO_USUARIO NVARCHAR2(20) NOT NULL,
  MENSAGEM NVARCHAR2(1000) NOT NULL,
  DATA_POSTAGEM DATE DEFAULT SYSDATE NOT NULL,
  TOTAL_CURTIDAS NUMBER DEFAULT 0 NOT NULL,
  TOTAL_COMENTARIOS NUMBER DEFAULT 0 NOT NULL,
  POST_DESTAQUE NUMBER(1) DEFAULT 0 NOT NULL,
  CONSTRAINT CK_FEED_POSTS_TIPO_USUARIO CHECK (TIPO_USUARIO IN ('VENDEDOR', 'GERENTE')),
  CONSTRAINT CK_FEED_POSTS_DESTAQUE CHECK (POST_DESTAQUE IN (0, 1))
);

CREATE SEQUENCE FEED_POSTS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_FEED_POSTS_BI
BEFORE INSERT ON FEED_POSTS
FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN
    :NEW.ID := FEED_POSTS_SEQ.NEXTVAL;
  END IF;
END;
/

CREATE TABLE FEED_COMENTARIOS (
  ID NUMBER PRIMARY KEY,
  POST_ID NUMBER NOT NULL,
  USUARIO_ID NUMBER NOT NULL,
  NOME_USUARIO NVARCHAR2(160) NOT NULL,
  COMENTARIO NVARCHAR2(500) NOT NULL,
  DATA_COMENTARIO DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT FK_FEED_COMENTARIOS_POST
    FOREIGN KEY (POST_ID) REFERENCES FEED_POSTS(ID) ON DELETE CASCADE
);

CREATE SEQUENCE FEED_COMENTARIOS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_FEED_COMENTARIOS_BI
BEFORE INSERT ON FEED_COMENTARIOS
FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN
    :NEW.ID := FEED_COMENTARIOS_SEQ.NEXTVAL;
  END IF;
END;
/

CREATE TABLE FEED_CURTIDAS (
  ID NUMBER PRIMARY KEY,
  POST_ID NUMBER NOT NULL,
  USUARIO_ID NUMBER NOT NULL,
  DATA_CURTIDA DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT FK_FEED_CURTIDAS_POST
    FOREIGN KEY (POST_ID) REFERENCES FEED_POSTS(ID) ON DELETE CASCADE,
  CONSTRAINT UQ_FEED_CURTIDAS_POST_USUARIO UNIQUE (POST_ID, USUARIO_ID)
);

CREATE SEQUENCE FEED_CURTIDAS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_FEED_CURTIDAS_BI
BEFORE INSERT ON FEED_CURTIDAS
FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN
    :NEW.ID := FEED_CURTIDAS_SEQ.NEXTVAL;
  END IF;
END;
/

CREATE INDEX IDX_FEED_POSTS_EMPRESA_DATA ON FEED_POSTS (EMPRESA_ID, POST_DESTAQUE, DATA_POSTAGEM DESC);
CREATE INDEX IDX_FEED_POSTS_USUARIO ON FEED_POSTS (USUARIO_ID);
CREATE INDEX IDX_FEED_POSTS_DATA ON FEED_POSTS (DATA_POSTAGEM DESC);

CREATE INDEX IDX_FEED_COMENTARIOS_POST ON FEED_COMENTARIOS (POST_ID);
CREATE INDEX IDX_FEED_COMENTARIOS_USUARIO ON FEED_COMENTARIOS (USUARIO_ID);
CREATE INDEX IDX_FEED_COMENTARIOS_DATA ON FEED_COMENTARIOS (DATA_COMENTARIO DESC);

CREATE INDEX IDX_FEED_CURTIDAS_POST ON FEED_CURTIDAS (POST_ID);
CREATE INDEX IDX_FEED_CURTIDAS_USUARIO ON FEED_CURTIDAS (USUARIO_ID);
CREATE INDEX IDX_FEED_CURTIDAS_DATA ON FEED_CURTIDAS (DATA_CURTIDA DESC);
