DECLARE
  v_total NUMBER := 0;
BEGIN
  SELECT COUNT(*)
    INTO v_total
    FROM USER_TABLES
   WHERE TABLE_NAME = 'CAMPANHA_LINKS';

  IF v_total = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE CAMPANHA_LINKS (
        id NUMBER(18) PRIMARY KEY,
        token VARCHAR2(80 CHAR) NOT NULL,
        campanha_id NUMBER(18) NOT NULL,
        campanha_cliente_id NUMBER(18) NOT NULL,
        cliente_id NUMBER(18),
        vendedor_id NUMBER(18),
        link_url VARCHAR2(500 CHAR),
        total_cliques NUMBER(10) DEFAULT 0 NOT NULL,
        primeiro_clique DATE,
        ultimo_clique DATE,
        converteu CHAR(1) DEFAULT 'N' NOT NULL,
        valor_conversao NUMBER(18, 2),
        data_criacao DATE DEFAULT SYSDATE NOT NULL,
        CONSTRAINT uq_camp_links_token UNIQUE (token),
        CONSTRAINT fk_camp_links_camp FOREIGN KEY (campanha_id)
          REFERENCES CAMPANHAS_ATIVACAO (id),
        CONSTRAINT fk_camp_links_cliente FOREIGN KEY (campanha_cliente_id)
          REFERENCES CAMPANHAS_ATIVACAO_CLIENTES (id),
        CONSTRAINT ck_camp_links_converteu CHECK (converteu IN ('S', 'N'))
      )
    ]';
  END IF;
END;
/

DECLARE
  v_total NUMBER := 0;
BEGIN
  SELECT COUNT(*)
    INTO v_total
    FROM USER_TABLES
   WHERE TABLE_NAME = 'CAMPANHA_EVENTOS';

  IF v_total = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE CAMPANHA_EVENTOS (
        id NUMBER(18) PRIMARY KEY,
        campanha_id NUMBER(18) NOT NULL,
        campanha_cliente_id NUMBER(18),
        cliente_id NUMBER(18),
        tipo_evento VARCHAR2(40 CHAR) NOT NULL,
        detalhe VARCHAR2(2000 CHAR),
        data_evento DATE DEFAULT SYSDATE NOT NULL,
        CONSTRAINT fk_camp_eventos_camp_v2 FOREIGN KEY (campanha_id)
          REFERENCES CAMPANHAS_ATIVACAO (id),
        CONSTRAINT fk_camp_eventos_cliente_v2 FOREIGN KEY (campanha_cliente_id)
          REFERENCES CAMPANHAS_ATIVACAO_CLIENTES (id)
      )
    ]';
  END IF;
END;
/

DECLARE
  v_total NUMBER := 0;
BEGIN
  SELECT COUNT(*)
    INTO v_total
    FROM USER_TAB_COLUMNS
   WHERE TABLE_NAME = 'CAMPANHAS_ATIVACAO_CLIENTES'
     AND COLUMN_NAME = 'LINK_TOKEN';

  IF v_total = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE CAMPANHAS_ATIVACAO_CLIENTES ADD (link_token VARCHAR2(80 CHAR))';
  END IF;
END;
/

DECLARE
  v_total NUMBER := 0;
BEGIN
  SELECT COUNT(*)
    INTO v_total
    FROM USER_TAB_COLUMNS
   WHERE TABLE_NAME = 'CAMPANHAS_ATIVACAO_CLIENTES'
     AND COLUMN_NAME = 'LINK_URL';

  IF v_total = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE CAMPANHAS_ATIVACAO_CLIENTES ADD (link_url VARCHAR2(500 CHAR))';
  END IF;
END;
/

DECLARE
  v_total NUMBER := 0;
BEGIN
  SELECT COUNT(*)
    INTO v_total
    FROM USER_TAB_COLUMNS
   WHERE TABLE_NAME = 'CAMPANHAS_ATIVACAO_CLIENTES'
     AND COLUMN_NAME = 'MESSAGE_ID';

  IF v_total = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE CAMPANHAS_ATIVACAO_CLIENTES ADD (message_id VARCHAR2(120 CHAR))';
  END IF;
END;
/

DECLARE
  v_total NUMBER := 0;
BEGIN
  SELECT COUNT(*)
    INTO v_total
    FROM USER_TAB_COLUMNS
   WHERE TABLE_NAME = 'CAMPANHAS_ATIVACAO_CLIENTES'
     AND COLUMN_NAME = 'ZAPI_ZAAP_ID';

  IF v_total = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE CAMPANHAS_ATIVACAO_CLIENTES ADD (zapi_zaap_id VARCHAR2(120 CHAR))';
  END IF;
END;
/

DECLARE
  v_total NUMBER := 0;
BEGIN
  SELECT COUNT(*)
    INTO v_total
    FROM USER_TAB_COLUMNS
   WHERE TABLE_NAME = 'CAMPANHAS_ATIVACAO_CLIENTES'
     AND COLUMN_NAME = 'DATA_ENVIO_ZAPI';

  IF v_total = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE CAMPANHAS_ATIVACAO_CLIENTES ADD (data_envio_zapi DATE)';
  END IF;
END;
/

DECLARE
  v_total NUMBER := 0;
BEGIN
  SELECT COUNT(*)
    INTO v_total
    FROM USER_TAB_COLUMNS
   WHERE TABLE_NAME = 'CAMPANHAS_ATIVACAO_CLIENTES'
     AND COLUMN_NAME = 'DETALHE_STATUS';

  IF v_total = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE CAMPANHAS_ATIVACAO_CLIENTES ADD (detalhe_status VARCHAR2(1000 CHAR))';
  END IF;
END;
/

DECLARE
  v_total NUMBER := 0;
BEGIN
  SELECT COUNT(*)
    INTO v_total
    FROM USER_TAB_COLUMNS
   WHERE TABLE_NAME = 'CAMPANHAS_ATIVACAO_CLIENTES'
     AND COLUMN_NAME = 'ERRO_ENVIO';

  IF v_total = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE CAMPANHAS_ATIVACAO_CLIENTES ADD (erro_envio VARCHAR2(1000 CHAR))';
  END IF;
END;
/

DECLARE
  v_total NUMBER := 0;
BEGIN
  SELECT COUNT(*)
    INTO v_total
    FROM USER_TAB_COLUMNS
   WHERE TABLE_NAME = 'CAMPANHAS_ATIVACAO_CLIENTES'
     AND COLUMN_NAME = 'ULTIMO_EVENTO_EM';

  IF v_total = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE CAMPANHAS_ATIVACAO_CLIENTES ADD (ultimo_evento_em DATE)';
  END IF;
END;
/

DECLARE
  v_total NUMBER := 0;
BEGIN
  SELECT COUNT(*)
    INTO v_total
    FROM USER_CONSTRAINTS
   WHERE TABLE_NAME = 'CAMPANHAS_ATIVACAO_CLIENTES'
     AND CONSTRAINT_NAME = 'CK_CAMP_ATIVACAO_STATUS_ENVIO';

  IF v_total > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE CAMPANHAS_ATIVACAO_CLIENTES DROP CONSTRAINT CK_CAMP_ATIVACAO_STATUS_ENVIO';
  END IF;
END;
/

DECLARE
  v_total NUMBER := 0;
BEGIN
  SELECT COUNT(*)
    INTO v_total
    FROM USER_CONSTRAINTS
   WHERE TABLE_NAME = 'CAMPANHAS_ATIVACAO_CLIENTES'
     AND CONSTRAINT_NAME = 'CK_CAMP_ATIVACAO_STATUS_ENVIO';

  IF v_total = 0 THEN
    EXECUTE IMMEDIATE q'[
      ALTER TABLE CAMPANHAS_ATIVACAO_CLIENTES
      ADD CONSTRAINT CK_CAMP_ATIVACAO_STATUS_ENVIO
      CHECK (status_envio IN ('PENDENTE', 'LINK_GERADO', 'ENVIADO_WEBHOOK', 'ENVIADO', 'ENTREGUE', 'LIDO', 'RESPONDIDO', 'FALHA'))
    ]';
  END IF;
END;
/

DECLARE
  v_total NUMBER := 0;
BEGIN
  SELECT COUNT(*)
    INTO v_total
    FROM USER_INDEXES
   WHERE INDEX_NAME = 'IDX_CAMP_LINKS_TOKEN';

  IF v_total = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_CAMP_LINKS_TOKEN ON CAMPANHA_LINKS (token)';
  END IF;
END;
/

DECLARE
  v_total NUMBER := 0;
BEGIN
  SELECT COUNT(*)
    INTO v_total
    FROM USER_INDEXES
   WHERE INDEX_NAME = 'IDX_CAMP_LINKS_CAMP';

  IF v_total = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_CAMP_LINKS_CAMP ON CAMPANHA_LINKS (campanha_id, campanha_cliente_id)';
  END IF;
END;
/

DECLARE
  v_total NUMBER := 0;
BEGIN
  SELECT COUNT(*)
    INTO v_total
    FROM USER_INDEXES
   WHERE INDEX_NAME = 'IDX_CAMP_EVENTOS_CAMP';

  IF v_total = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_CAMP_EVENTOS_CAMP ON CAMPANHA_EVENTOS (campanha_id, tipo_evento, data_evento)';
  END IF;
END;
/

DECLARE
  v_total NUMBER := 0;
BEGIN
  SELECT COUNT(*)
    INTO v_total
    FROM USER_INDEXES
   WHERE INDEX_NAME = 'IDX_CAMP_EVENTOS_CLIENTE';

  IF v_total = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_CAMP_EVENTOS_CLIENTE ON CAMPANHA_EVENTOS (campanha_cliente_id, cliente_id)';
  END IF;
END;
/

DECLARE
  v_total NUMBER := 0;
BEGIN
  SELECT COUNT(*)
    INTO v_total
    FROM USER_INDEXES
   WHERE INDEX_NAME = 'IDX_CAMP_CLIENTES_MESSAGE';

  IF v_total = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_CAMP_CLIENTES_MESSAGE ON CAMPANHAS_ATIVACAO_CLIENTES (message_id, zapi_zaap_id)';
  END IF;
END;
/

COMMENT ON TABLE CAMPANHA_LINKS IS 'Links individuais da campanha de ativacao com rastreamento da Central de Negociacao.';
COMMENT ON TABLE CAMPANHA_EVENTOS IS 'Historico de eventos da campanha de ativacao com entregas, leituras, cliques e conversoes.';
COMMENT ON COLUMN CAMPANHAS_ATIVACAO_CLIENTES.link_token IS 'Token unico gerado para a Central de Negociacao.';
COMMENT ON COLUMN CAMPANHAS_ATIVACAO_CLIENTES.link_url IS 'URL publica da Central de Negociacao do cliente.';
COMMENT ON COLUMN CAMPANHAS_ATIVACAO_CLIENTES.message_id IS 'Identificador principal da mensagem retornado pela Z-API.';
COMMENT ON COLUMN CAMPANHAS_ATIVACAO_CLIENTES.zapi_zaap_id IS 'Identificador secundario retornado pela Z-API.';
COMMENT ON COLUMN CAMPANHAS_ATIVACAO_CLIENTES.data_envio_zapi IS 'Momento em que a Z-API aceitou o envio da mensagem.';
