-- =============================================================================
-- DDL - SCHEMA DM_VENDAS
-- Gerado em: 2026-06-24
-- Ordem de execucao: sequencias > tabelas pai > tabelas filhas > indices >
--                    views > triggers
-- =============================================================================

-- =============================================================================
-- BLOCO 0: SEQUENCES
-- =============================================================================

CREATE SEQUENCE "DM_VENDAS"."OBJETIVOS_VENDEDOR_SEQ" START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE "DM_VENDAS"."PERFIL_VENDEDOR_SEQ" START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE "DM_VENDAS"."DESAFIOS_COMERCIAIS_SEQ" START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE "DM_VENDAS"."DESAFIOS_COMERCIAIS_METAS_SEQ" START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE "DM_VENDAS"."DESAFIOS_COMERCIAIS_VENDEDORES_SEQ" START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE "DM_VENDAS"."DESAFIOS_COMERCIAIS_PROGRESSO_SEQ" START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE "DM_VENDAS"."DESAFIOS_COMERCIAIS_LOG_SEQ" START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE "DM_VENDAS"."FEED_POSTS_SEQ" START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE "DM_VENDAS"."FEED_COMENTARIOS_SEQ" START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE "DM_VENDAS"."FEED_CURTIDAS_SEQ" START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE "DM_VENDAS"."ORGANIZACOES_SEQ" START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;


-- =============================================================================
-- BLOCO 1: TABELAS INDEPENDENTES (sem FK para outras tabelas do schema)
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1.1 CAMPANHAS_ATIVACAO
-- Cabecalho das campanhas da central de ativacao de clientes.
-- -----------------------------------------------------------------------------
CREATE TABLE "DM_VENDAS"."CAMPANHAS_ATIVACAO"
(
    "ID"                       NUMBER(18,0),
    "SEGMENTO"                 VARCHAR2(60 CHAR)  NOT NULL ENABLE,
    "TEMPLATE_ID"              NUMBER(18,0),
    "MENSAGEM_BASE"            VARCHAR2(2000 CHAR),
    "TOTAL_CLIENTES"           NUMBER(10,0)       DEFAULT 0  NOT NULL ENABLE,
    "TOTAL_COM_TELEFONE"       NUMBER(10,0)       DEFAULT 0  NOT NULL ENABLE,
    "TOTAL_SEM_TELEFONE"       NUMBER(10,0)       DEFAULT 0  NOT NULL ENABLE,
    "VENDEDOR_ID"              NUMBER(18,0),
    "EMPRESA_ID"               NUMBER(18,0),
    "DATA_CONFIRMACAO"         DATE,
    "ID_USUARIO_CONFIRMACAO"   NUMBER(18,0),
    "NOME_USUARIO_CONFIRMACAO" VARCHAR2(255 CHAR),
    "DATA_CRIACAO"             DATE               DEFAULT SYSDATE NOT NULL ENABLE,
    CONSTRAINT "PK_CAMPANHAS_ATIVACAO" PRIMARY KEY ("ID")
        USING INDEX TABLESPACE "DADOS"
)
SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
NOCOMPRESS LOGGING
TABLESPACE "DADOS";

COMMENT ON TABLE  "DM_VENDAS"."CAMPANHAS_ATIVACAO"                             IS 'Cabecalho das campanhas da central de ativacao de clientes.';
COMMENT ON COLUMN "DM_VENDAS"."CAMPANHAS_ATIVACAO"."DATA_CONFIRMACAO"          IS 'Data em que a campanha foi confirmada.';
COMMENT ON COLUMN "DM_VENDAS"."CAMPANHAS_ATIVACAO"."ID_USUARIO_CONFIRMACAO"    IS 'Usuario que confirmou a campanha.';
COMMENT ON COLUMN "DM_VENDAS"."CAMPANHAS_ATIVACAO"."NOME_USUARIO_CONFIRMACAO"  IS 'Nome do usuario que confirmou a campanha.';

CREATE INDEX "DM_VENDAS"."IDX_CAMP_ATIVACAO_LOOKUP"
    ON "DM_VENDAS"."CAMPANHAS_ATIVACAO" ("EMPRESA_ID", "VENDEDOR_ID", "DATA_CRIACAO")
    TABLESPACE "DADOS";

CREATE INDEX "DM_VENDAS"."IDX_CAMP_ATIVACAO_SEGMENTO"
    ON "DM_VENDAS"."CAMPANHAS_ATIVACAO" ("SEGMENTO", "DATA_CRIACAO")
    TABLESPACE "DADOS";


-- -----------------------------------------------------------------------------
-- 1.2 DESAFIOS_COMERCIAIS
-- Cabecalho do desafio/campanha.
-- -----------------------------------------------------------------------------
CREATE TABLE "DM_VENDAS"."DESAFIOS_COMERCIAIS"
(
    "ID_DESAFIO"     NUMBER(18,0),
    "EMPRESA_ID"     NUMBER(18,0),
    "TITULO"         VARCHAR2(160 CHAR) NOT NULL ENABLE,
    "DESCRICAO"      VARCHAR2(500 CHAR),
    "DATA_INICIO"    DATE               NOT NULL ENABLE,
    "DATA_FIM"       DATE               NOT NULL ENABLE,
    "STATUS"         VARCHAR2(20 CHAR)  DEFAULT 'RASCUNHO' NOT NULL ENABLE,
    "EXIGE_ACEITE"   CHAR(1 BYTE)       DEFAULT 'S'        NOT NULL ENABLE,
    "CRIADO_POR"     VARCHAR2(120 CHAR),
    "CRIADO_EM"      DATE               DEFAULT SYSDATE    NOT NULL ENABLE,
    "ATUALIZADO_EM"  DATE               DEFAULT SYSDATE    NOT NULL ENABLE,
    CONSTRAINT "CK_DESAFIOS_STATUS"
        CHECK (status IN (
            'RASCUNHO','AGENDADO','ATIVO','ENCERRADO',
            'ENCERRADO_AUTOMATICO','ENCERRADO_MANUAL','CANCELADO'
        )) ENABLE,
    CONSTRAINT "CK_DESAFIOS_ACEITE"
        CHECK (exige_aceite IN ('S','N')) ENABLE,
    CONSTRAINT "PK_DESAFIOS_COMERCIAIS" PRIMARY KEY ("ID_DESAFIO")
        USING INDEX TABLESPACE "DADOS"
)
SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
NOCOMPRESS LOGGING
TABLESPACE "DADOS";

COMMENT ON TABLE "DM_VENDAS"."DESAFIOS_COMERCIAIS" IS 'Cabecalho do desafio/campanha.';

CREATE INDEX "DM_VENDAS"."IDX_DESAFIOS_EMPRESA"
    ON "DM_VENDAS"."DESAFIOS_COMERCIAIS" ("EMPRESA_ID", "STATUS")
    TABLESPACE "DADOS";

CREATE INDEX "DM_VENDAS"."IDX_DESAFIOS_STATUS_PERIODO"
    ON "DM_VENDAS"."DESAFIOS_COMERCIAIS" ("STATUS", "DATA_INICIO", "DATA_FIM")
    TABLESPACE "DADOS";


-- -----------------------------------------------------------------------------
-- 1.3 FEED_POSTS
-- Posts do feed de noticias entre vendedores e gerentes.
-- Nota: FEED_COMENTARIOS e FEED_CURTIDAS referenciam esta tabela,
--       portanto ela deve existir antes delas.
-- -----------------------------------------------------------------------------
CREATE TABLE "DM_VENDAS"."FEED_POSTS"
(
    "ID"                      NUMBER,
    "EMPRESA_ID"              NUMBER           NOT NULL ENABLE,
    "USUARIO_ID"              NUMBER           NOT NULL ENABLE,
    "NOME_USUARIO"            NVARCHAR2(160)   NOT NULL ENABLE,
    "TIPO_USUARIO"            NVARCHAR2(20)    NOT NULL ENABLE,
    "MENSAGEM"                NVARCHAR2(1000)  NOT NULL ENABLE,
    "DATA_POSTAGEM"           DATE             DEFAULT SYSDATE NOT NULL ENABLE,
    "TOTAL_CURTIDAS"          NUMBER           DEFAULT 0       NOT NULL ENABLE,
    "TOTAL_COMENTARIOS"       NUMBER           DEFAULT 0       NOT NULL ENABLE,
    "POST_DESTAQUE"           NUMBER(1,0)      DEFAULT 0       NOT NULL ENABLE,
    "VISIBILIDADE"            VARCHAR2(20 BYTE) DEFAULT 'PUBLICO' NOT NULL ENABLE,
    "DESTINATARIO_USUARIO_ID" NUMBER,
    "DESTINATARIO_NOME"       NVARCHAR2(255),
    "DESTINATARIO_TIPO"       VARCHAR2(30 BYTE),
    CONSTRAINT "CK_FEED_POSTS_TIPO_USUARIO"
        CHECK (TIPO_USUARIO IN ('VENDEDOR','GERENTE')) ENABLE,
    CONSTRAINT "CK_FEED_POSTS_DESTAQUE"
        CHECK (POST_DESTAQUE IN (0,1)) ENABLE,
    CONSTRAINT "PK_FEED_POSTS" PRIMARY KEY ("ID")
        USING INDEX TABLESPACE "DADOS"
)
SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
NOCOMPRESS LOGGING
TABLESPACE "DADOS";

CREATE INDEX "DM_VENDAS"."IDX_FEED_POSTS_AUTOR_DEST"
    ON "DM_VENDAS"."FEED_POSTS" ("EMPRESA_ID", "USUARIO_ID", "DESTINATARIO_USUARIO_ID")
    TABLESPACE "DADOS";

CREATE INDEX "DM_VENDAS"."IDX_FEED_POSTS_DATA"
    ON "DM_VENDAS"."FEED_POSTS" ("DATA_POSTAGEM" DESC)
    TABLESPACE "DADOS";

CREATE INDEX "DM_VENDAS"."IDX_FEED_POSTS_EMPRESA_DATA"
    ON "DM_VENDAS"."FEED_POSTS" ("EMPRESA_ID", "POST_DESTAQUE", "DATA_POSTAGEM" DESC)
    TABLESPACE "DADOS";

CREATE INDEX "DM_VENDAS"."IDX_FEED_POSTS_USUARIO"
    ON "DM_VENDAS"."FEED_POSTS" ("USUARIO_ID")
    TABLESPACE "DADOS";

CREATE INDEX "DM_VENDAS"."IDX_FEED_POSTS_VISIBILIDADE"
    ON "DM_VENDAS"."FEED_POSTS" ("EMPRESA_ID", "VISIBILIDADE", "DESTINATARIO_USUARIO_ID")
    TABLESPACE "DADOS";


-- -----------------------------------------------------------------------------
-- 1.4 INSIGHTS_VENDEDOR
-- Cache de insights gerados por vendedor e data de referencia.
-- -----------------------------------------------------------------------------
CREATE TABLE "DM_VENDAS"."INSIGHTS_VENDEDOR"
(
    "VENDEDOR_ID"     NUMBER       NOT NULL ENABLE,
    "DATA_REFERENCIA" DATE         NOT NULL ENABLE,
    "INSIGHTS_JSON"   CLOB         NOT NULL ENABLE,
    "ORIGEM"          VARCHAR2(50 BYTE),
    "PAYLOAD_JSON"    CLOB,
    "ATUALIZADO_EM"   DATE         DEFAULT SYSDATE NOT NULL ENABLE
)
SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
NOCOMPRESS LOGGING
TABLESPACE "DADOS"
LOB ("INSIGHTS_JSON") STORE AS SECUREFILE (
    TABLESPACE "DADOS" ENABLE STORAGE IN ROW CHUNK 8192
    NOCACHE LOGGING NOCOMPRESS KEEP_DUPLICATES)
LOB ("PAYLOAD_JSON") STORE AS SECUREFILE (
    TABLESPACE "DADOS" ENABLE STORAGE IN ROW CHUNK 8192
    NOCACHE LOGGING NOCOMPRESS KEEP_DUPLICATES);

CREATE UNIQUE INDEX "DM_VENDAS"."UX_INSIGHTS_VENDEDOR"
    ON "DM_VENDAS"."INSIGHTS_VENDEDOR" ("VENDEDOR_ID", "DATA_REFERENCIA")
    TABLESPACE "DADOS";


-- -----------------------------------------------------------------------------
-- 1.5 ORGANIZACOES
-- Conexoes Oracle cadastradas para cada organizacao/cliente.
-- -----------------------------------------------------------------------------
CREATE TABLE "DM_VENDAS"."ORGANIZACOES"
(
    "ID"                NUMBER(18,0),
    "NOME"              VARCHAR2(200 CHAR)  NOT NULL ENABLE,
    "DESCRICAO"         VARCHAR2(1000 CHAR),
    "STATUS"            VARCHAR2(10 CHAR)   DEFAULT 'ATIVA' NOT NULL ENABLE,
    "DB_USER"           VARCHAR2(200 CHAR)  NOT NULL ENABLE,
    "DB_PASSWORD_ENC"   VARCHAR2(500 CHAR)  NOT NULL ENABLE,
    "DB_CONNECT_STRING" VARCHAR2(500 CHAR)  NOT NULL ENABLE,
    "CRIADO_EM"         DATE                DEFAULT SYSDATE NOT NULL ENABLE,
    "ATUALIZADO_EM"     DATE                DEFAULT SYSDATE NOT NULL ENABLE,
    CONSTRAINT "CK_ORGANIZACOES_STATUS"
        CHECK (status IN ('ATIVA','INATIVA')) ENABLE,
    CONSTRAINT "PK_ORGANIZACOES" PRIMARY KEY ("ID")
        USING INDEX TABLESPACE "DADOS"
)
SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
NOCOMPRESS LOGGING
TABLESPACE "DADOS";

COMMENT ON TABLE "DM_VENDAS"."ORGANIZACOES" IS 'Conexoes Oracle cadastradas para cada organizacao/cliente.';

CREATE INDEX "DM_VENDAS"."IDX_ORGANIZACOES_STATUS"
    ON "DM_VENDAS"."ORGANIZACOES" ("STATUS")
    TABLESPACE "DADOS";


-- -----------------------------------------------------------------------------
-- 1.6 GM_TB_FORNECEDORES_LOGIN
-- Credenciais de acesso para parceiros da industria.
-- Mantem o nome legado porque a rota de industria usa esse contrato.
-- -----------------------------------------------------------------------------
CREATE TABLE "DM_VENDAS"."GM_TB_FORNECEDORES_LOGIN"
(
    "ID"             NUMBER GENERATED BY DEFAULT AS IDENTITY
                         MINVALUE 1 MAXVALUE 9999999999999999999999999999
                         INCREMENT BY 1 START WITH 1 CACHE 20
                         NOORDER NOCYCLE NOKEEP NOSCALE NOT NULL ENABLE,
    "NOME"           VARCHAR2(160 CHAR) NOT NULL ENABLE,
    "CODIGO"         VARCHAR2(60 CHAR)  NOT NULL ENABLE,
    "SENHA_HASH"     VARCHAR2(255 CHAR) NOT NULL ENABLE,
    "MARCA"          VARCHAR2(120 CHAR) NOT NULL ENABLE,
    "ATIVO"          CHAR(1 BYTE)       DEFAULT 'S' NOT NULL ENABLE,
    "CRIADO_EM"      DATE               DEFAULT SYSDATE NOT NULL ENABLE,
    "ATUALIZADO_EM"  DATE               DEFAULT SYSDATE NOT NULL ENABLE,
    CONSTRAINT "UK_FORNECEDORES_LOGIN_CODIGO" UNIQUE ("CODIGO")
        USING INDEX TABLESPACE "DADOS",
    CONSTRAINT "CK_FORNECEDORES_LOGIN_ATIVO"
        CHECK (ativo IN ('S','N')) ENABLE,
    CONSTRAINT "PK_FORNECEDORES_LOGIN" PRIMARY KEY ("ID")
        USING INDEX TABLESPACE "DADOS"
)
SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
NOCOMPRESS LOGGING
TABLESPACE "DADOS";

COMMENT ON TABLE  "DM_VENDAS"."GM_TB_FORNECEDORES_LOGIN"              IS 'Credenciais de acesso para parceiros da industria.';
COMMENT ON COLUMN "DM_VENDAS"."GM_TB_FORNECEDORES_LOGIN"."CODIGO"     IS 'Codigo de login do parceiro, por exemplo SUVINIL01.';
COMMENT ON COLUMN "DM_VENDAS"."GM_TB_FORNECEDORES_LOGIN"."SENHA_HASH" IS 'Senha protegida com bcrypt.';
COMMENT ON COLUMN "DM_VENDAS"."GM_TB_FORNECEDORES_LOGIN"."MARCA"      IS 'Marca usada para filtrar os dados do portal.';

CREATE INDEX "DM_VENDAS"."IDX_FORNECEDORES_LOGIN_MARCA"
    ON "DM_VENDAS"."GM_TB_FORNECEDORES_LOGIN" ("MARCA", "ATIVO")
    TABLESPACE "DADOS";


-- -----------------------------------------------------------------------------
-- 1.7 OBJETIVOS_VENDEDOR
-- Objetivo financeiro pessoal do vendedor.
-- -----------------------------------------------------------------------------
CREATE TABLE "DM_VENDAS"."OBJETIVOS_VENDEDOR"
(
    "ID_OBJETIVO"    NUMBER(18,0),
    "EMPRESA_ID"     NUMBER(18,0)   NOT NULL ENABLE,
    "VENDEDOR_ID"    NUMBER(18,0)   NOT NULL ENABLE,
    "SK_VENDEDOR"    NUMBER(18,0),
    "NOME_OBJETIVO"  VARCHAR2(160 CHAR) NOT NULL ENABLE,
    "VALOR_OBJETIVO" NUMBER(18,2)   NOT NULL ENABLE,
    "DATA_LIMITE"    DATE           NOT NULL ENABLE,
    "ATIVO"          CHAR(1 BYTE)   DEFAULT 'S' NOT NULL ENABLE,
    "CRIADO_EM"      DATE           DEFAULT SYSDATE NOT NULL ENABLE,
    "ATUALIZADO_EM"  DATE           DEFAULT SYSDATE NOT NULL ENABLE,
    CONSTRAINT "CK_OBJETIVOS_VENDEDOR_ATIVO"
        CHECK (ativo IN ('S','N')) ENABLE,
    CONSTRAINT "PK_OBJETIVOS_VENDEDOR" PRIMARY KEY ("ID_OBJETIVO")
        USING INDEX TABLESPACE "DADOS"
)
SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
NOCOMPRESS LOGGING
TABLESPACE "DADOS";

COMMENT ON TABLE  "DM_VENDAS"."OBJETIVOS_VENDEDOR"                  IS 'Objetivo financeiro pessoal do vendedor.';
COMMENT ON COLUMN "DM_VENDAS"."OBJETIVOS_VENDEDOR"."VALOR_OBJETIVO" IS 'Valor total que o vendedor deseja conquistar.';
COMMENT ON COLUMN "DM_VENDAS"."OBJETIVOS_VENDEDOR"."DATA_LIMITE"    IS 'Data alvo para concluir a conquista pessoal.';

CREATE INDEX "DM_VENDAS"."IDX_OBJETIVOS_VENDEDOR_LOOKUP"
    ON "DM_VENDAS"."OBJETIVOS_VENDEDOR" ("SK_VENDEDOR", "VENDEDOR_ID", "EMPRESA_ID", "ATUALIZADO_EM")
    TABLESPACE "DADOS";


-- -----------------------------------------------------------------------------
-- 1.8 PERFIL_VENDEDOR
-- Perfil pessoal do vendedor para personalizacao do painel Minha Meta de Vida.
-- -----------------------------------------------------------------------------
CREATE TABLE "DM_VENDAS"."PERFIL_VENDEDOR"
(
    "ID"                    NUMBER(18,0),
    "VENDEDOR_ID"           NUMBER(18,0)   NOT NULL ENABLE,
    "EMPRESA_ID"            NUMBER(18,0)   NOT NULL ENABLE,
    "RENDA_DESEJADA"        NUMBER(18,2),
    "MOTIVO_TRABALHO"       VARCHAR2(200 CHAR),
    "PARA_QUEM_TRABALHA"    VARCHAR2(200 CHAR),
    "OBJETIVOS_PESSOAIS"    VARCHAR2(400 CHAR),
    "PREFERENCIAS_PRODUTO"  VARCHAR2(160 CHAR),
    "CRIADO_EM"             DATE           DEFAULT SYSDATE NOT NULL ENABLE,
    "SALARIO_FIXO"          NUMBER(18,2),
    "COMISSAO_DESEJADA"     NUMBER(18,2),
    CONSTRAINT "PK_PERFIL_VENDEDOR" PRIMARY KEY ("ID")
        USING INDEX TABLESPACE "DADOS"
)
SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
NOCOMPRESS LOGGING
TABLESPACE "DADOS";

COMMENT ON TABLE  "DM_VENDAS"."PERFIL_VENDEDOR"                        IS 'Perfil pessoal do vendedor para personalizacao do painel Minha Meta de Vida.';
COMMENT ON COLUMN "DM_VENDAS"."PERFIL_VENDEDOR"."RENDA_DESEJADA"       IS 'Valor de renda que o vendedor deseja atingir no mes.';
COMMENT ON COLUMN "DM_VENDAS"."PERFIL_VENDEDOR"."PREFERENCIAS_PRODUTO" IS 'Categoria ou familia de produtos preferida pelo vendedor.';
COMMENT ON COLUMN "DM_VENDAS"."PERFIL_VENDEDOR"."SALARIO_FIXO"         IS 'Valor fixo mensal informado pelo vendedor.';
COMMENT ON COLUMN "DM_VENDAS"."PERFIL_VENDEDOR"."COMISSAO_DESEJADA"    IS 'Valor de comissao que o vendedor deseja conquistar para complementar o salario.';

CREATE UNIQUE INDEX "DM_VENDAS"."UK_PERFIL_VENDEDOR_LOOKUP"
    ON "DM_VENDAS"."PERFIL_VENDEDOR" ("EMPRESA_ID", "VENDEDOR_ID")
    TABLESPACE "DADOS";


-- -----------------------------------------------------------------------------
-- 1.9 TEMPLATES_MENSAGENS
-- Templates de mensagens para campanhas.
-- -----------------------------------------------------------------------------
CREATE TABLE "DM_VENDAS"."TEMPLATES_MENSAGENS"
(
    "ID"                  NUMBER GENERATED BY DEFAULT AS IDENTITY
                              MINVALUE 1 MAXVALUE 9999999999999999999999999999
                              INCREMENT BY 1 START WITH 1 CACHE 20
                              NOORDER NOCYCLE NOKEEP NOSCALE NOT NULL ENABLE,
    "NOME_TEMPLATE"       VARCHAR2(150 CHAR) NOT NULL ENABLE,
    "TIPO"                VARCHAR2(40 CHAR)  NOT NULL ENABLE,
    "CLASSIFICACAO_RFV"   VARCHAR2(60 CHAR),
    "MENSAGEM"            CLOB               NOT NULL ENABLE,
    "ESCOPO"              VARCHAR2(30 CHAR)  NOT NULL ENABLE,
    "VENDEDOR_ID"         NUMBER,
    "EMPRESA_ID"          NUMBER,
    "DATA_CRIACAO"        DATE               DEFAULT SYSDATE NOT NULL ENABLE,
    "DATA_ATUALIZACAO"    DATE               DEFAULT SYSDATE NOT NULL ENABLE,
    "USUARIO_CRIACAO"     VARCHAR2(100 CHAR),
    "USUARIO_ATUALIZACAO" VARCHAR2(100 CHAR),
    CONSTRAINT "CK_TM_TIPO"   CHECK (TIPO   IN ('PADRAO','PERSONALIZADO','AUTOMACAO')) ENABLE,
    CONSTRAINT "CK_TM_ESCOPO" CHECK (ESCOPO IN ('SISTEMA','EMPRESA','USUARIO'))        ENABLE,
    CONSTRAINT "PK_TEMPLATES_MENSAGENS" PRIMARY KEY ("ID")
        USING INDEX TABLESPACE "DADOS"
)
SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
NOCOMPRESS LOGGING
TABLESPACE "DADOS"
LOB ("MENSAGEM") STORE AS SECUREFILE (
    TABLESPACE "DADOS" ENABLE STORAGE IN ROW CHUNK 8192
    NOCACHE LOGGING NOCOMPRESS KEEP_DUPLICATES);

CREATE INDEX "DM_VENDAS"."IDX_TM_CLASSIFICACAO_RFV"
    ON "DM_VENDAS"."TEMPLATES_MENSAGENS" ("CLASSIFICACAO_RFV") TABLESPACE "DADOS";

CREATE INDEX "DM_VENDAS"."IDX_TM_DATA_CRIACAO"
    ON "DM_VENDAS"."TEMPLATES_MENSAGENS" ("DATA_CRIACAO")      TABLESPACE "DADOS";

CREATE INDEX "DM_VENDAS"."IDX_TM_EMPRESA_ID"
    ON "DM_VENDAS"."TEMPLATES_MENSAGENS" ("EMPRESA_ID")        TABLESPACE "DADOS";

CREATE INDEX "DM_VENDAS"."IDX_TM_VENDEDOR_ID"
    ON "DM_VENDAS"."TEMPLATES_MENSAGENS" ("VENDEDOR_ID")       TABLESPACE "DADOS";


-- =============================================================================
-- BLOCO 2: TABELAS FILHAS DE CAMPANHAS_ATIVACAO
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 2.1 CAMPANHAS_ATIVACAO_CLIENTES
-- Clientes vinculados a cada campanha de ativacao.
-- Depende de: CAMPANHAS_ATIVACAO
-- -----------------------------------------------------------------------------
CREATE TABLE "DM_VENDAS"."CAMPANHAS_ATIVACAO_CLIENTES"
(
    "ID"               NUMBER(18,0),
    "CAMPANHA_ID"      NUMBER(18,0)    NOT NULL ENABLE,
    "SK_CLIENTE"       NUMBER(18,0),
    "NOME_CLIENTE"     VARCHAR2(160 CHAR),
    "TELEFONE"         VARCHAR2(30 CHAR),
    "CLASSIFICACAO_RFV" VARCHAR2(80 CHAR),
    "ULTIMA_COMPRA"    DATE,
    "VALOR_ORCAMENTO"  NUMBER(18,2),
    "DATA_ORCAMENTO"   DATE,
    "MENSAGEM_FINAL"   VARCHAR2(2000 CHAR),
    "STATUS_ENVIO"     VARCHAR2(30 CHAR)  DEFAULT 'PENDENTE' NOT NULL ENABLE,
    "LINK_TOKEN"       VARCHAR2(80 CHAR),
    "LINK_URL"         VARCHAR2(500 CHAR),
    "MESSAGE_ID"       VARCHAR2(120 CHAR),
    "ZAPI_ZAAP_ID"     VARCHAR2(120 CHAR),
    "DATA_ENVIO_ZAPI"  DATE,
    "DETALHE_STATUS"   VARCHAR2(1000 CHAR),
    "ERRO_ENVIO"       VARCHAR2(1000 CHAR),
    "ULTIMO_EVENTO_EM" DATE,
    CONSTRAINT "CK_CAMP_ATIVACAO_STATUS_ENVIO"
        CHECK (status_envio IN
            ('PENDENTE','LINK_GERADO','ENVIADO_WEBHOOK','ENVIADO',
             'ENTREGUE','LIDO','RESPONDIDO','FALHA')) ENABLE,
    CONSTRAINT "PK_CAMPANHAS_ATIVACAO_CLIENTES" PRIMARY KEY ("ID")
        USING INDEX TABLESPACE "DADOS",
    CONSTRAINT "FK_CAMP_ATIVACAO_CLIENTE_CAMP"
        FOREIGN KEY ("CAMPANHA_ID")
        REFERENCES "DM_VENDAS"."CAMPANHAS_ATIVACAO" ("ID") ENABLE
)
SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
NOCOMPRESS LOGGING
TABLESPACE "DADOS";

COMMENT ON TABLE  "DM_VENDAS"."CAMPANHAS_ATIVACAO_CLIENTES"                  IS 'Clientes vinculados a cada campanha de ativacao.';
COMMENT ON COLUMN "DM_VENDAS"."CAMPANHAS_ATIVACAO_CLIENTES"."MENSAGEM_FINAL" IS 'Mensagem personalizada final enviada ao cliente.';
COMMENT ON COLUMN "DM_VENDAS"."CAMPANHAS_ATIVACAO_CLIENTES"."STATUS_ENVIO"   IS 'Status do preparo/envio da campanha para o cliente.';

CREATE INDEX "DM_VENDAS"."IDX_CAMP_ATIV_CLIENTES_CAMP"
    ON "DM_VENDAS"."CAMPANHAS_ATIVACAO_CLIENTES" ("CAMPANHA_ID", "STATUS_ENVIO")
    TABLESPACE "DADOS";

CREATE INDEX "DM_VENDAS"."IDX_CAMP_ATIV_CLIENTE_SK"
    ON "DM_VENDAS"."CAMPANHAS_ATIVACAO_CLIENTES" ("SK_CLIENTE", "CAMPANHA_ID")
    TABLESPACE "DADOS";


-- =============================================================================
-- BLOCO 3: TABELAS FILHAS DE CAMPANHAS_ATIVACAO + CAMPANHAS_ATIVACAO_CLIENTES
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 3.1 CAMPANHA_EVENTOS
-- Depende de: CAMPANHAS_ATIVACAO, CAMPANHAS_ATIVACAO_CLIENTES
-- -----------------------------------------------------------------------------
CREATE TABLE "DM_VENDAS"."CAMPANHA_EVENTOS"
(
    "ID"                  NUMBER(18,0),
    "CAMPANHA_ID"         NUMBER(18,0)    NOT NULL ENABLE,
    "CAMPANHA_CLIENTE_ID" NUMBER(18,0),
    "CLIENTE_ID"          NUMBER(18,0),
    "TIPO_EVENTO"         VARCHAR2(40 CHAR) NOT NULL ENABLE,
    "DETALHE"             VARCHAR2(2000 CHAR),
    "DATA_EVENTO"         DATE             DEFAULT SYSDATE NOT NULL ENABLE,
    CONSTRAINT "PK_CAMPANHA_EVENTOS" PRIMARY KEY ("ID")
        USING INDEX TABLESPACE "DADOS",
    CONSTRAINT "FK_CAMP_EVENTOS_CAMP_V2"
        FOREIGN KEY ("CAMPANHA_ID")
        REFERENCES "DM_VENDAS"."CAMPANHAS_ATIVACAO" ("ID") ENABLE,
    CONSTRAINT "FK_CAMP_EVENTOS_CLIENTE_V2"
        FOREIGN KEY ("CAMPANHA_CLIENTE_ID")
        REFERENCES "DM_VENDAS"."CAMPANHAS_ATIVACAO_CLIENTES" ("ID") ENABLE
)
SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
NOCOMPRESS LOGGING
TABLESPACE "DADOS";


-- -----------------------------------------------------------------------------
-- 3.2 CAMPANHA_LINKS
-- Depende de: CAMPANHAS_ATIVACAO, CAMPANHAS_ATIVACAO_CLIENTES
-- -----------------------------------------------------------------------------
CREATE TABLE "DM_VENDAS"."CAMPANHA_LINKS"
(
    "ID"                  NUMBER(18,0),
    "TOKEN"               VARCHAR2(80 CHAR)  NOT NULL ENABLE,
    "CAMPANHA_ID"         NUMBER(18,0)       NOT NULL ENABLE,
    "CAMPANHA_CLIENTE_ID" NUMBER(18,0)       NOT NULL ENABLE,
    "CLIENTE_ID"          NUMBER(18,0),
    "VENDEDOR_ID"         NUMBER(18,0),
    "LINK_URL"            VARCHAR2(500 CHAR),
    "TOTAL_CLIQUES"       NUMBER(10,0)       DEFAULT 0   NOT NULL ENABLE,
    "PRIMEIRO_CLIQUE"     DATE,
    "ULTIMO_CLIQUE"       DATE,
    "CONVERTEU"           CHAR(1 BYTE)       DEFAULT 'N' NOT NULL ENABLE,
    "VALOR_CONVERSAO"     NUMBER(18,2),
    "DATA_CRIACAO"        DATE               DEFAULT SYSDATE NOT NULL ENABLE,
    CONSTRAINT "CK_CAMP_LINKS_CONVERTEU"
        CHECK (converteu IN ('S','N')) ENABLE,
    CONSTRAINT "PK_CAMPANHA_LINKS" PRIMARY KEY ("ID")
        USING INDEX TABLESPACE "DADOS",
    CONSTRAINT "UQ_CAMP_LINKS_TOKEN"
        UNIQUE ("TOKEN")
        USING INDEX TABLESPACE "DADOS",
    CONSTRAINT "FK_CAMP_LINKS_CAMP"
        FOREIGN KEY ("CAMPANHA_ID")
        REFERENCES "DM_VENDAS"."CAMPANHAS_ATIVACAO" ("ID") ENABLE,
    CONSTRAINT "FK_CAMP_LINKS_CLIENTE"
        FOREIGN KEY ("CAMPANHA_CLIENTE_ID")
        REFERENCES "DM_VENDAS"."CAMPANHAS_ATIVACAO_CLIENTES" ("ID") ENABLE
)
SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
NOCOMPRESS LOGGING
TABLESPACE "DADOS";


-- =============================================================================
-- BLOCO 4: TABELAS FILHAS DE DESAFIOS_COMERCIAIS
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 4.1 DESAFIOS_COMERCIAIS_LOG
-- Historico dos eventos do desafio.
-- Depende de: DESAFIOS_COMERCIAIS
-- -----------------------------------------------------------------------------
CREATE TABLE "DM_VENDAS"."DESAFIOS_COMERCIAIS_LOG"
(
    "ID"          NUMBER(18,0),
    "ID_DESAFIO"  NUMBER(18,0)    NOT NULL ENABLE,
    "SK_VENDEDOR" NUMBER(18,0),
    "EVENTO"      VARCHAR2(40 CHAR) NOT NULL ENABLE,
    "DESCRICAO"   VARCHAR2(500 CHAR),
    "DATA_EVENTO" DATE             DEFAULT SYSDATE NOT NULL ENABLE,
    CONSTRAINT "PK_DESAFIOS_COMERCIAIS_LOG" PRIMARY KEY ("ID")
        USING INDEX TABLESPACE "DADOS",
    CONSTRAINT "FK_DESAFIOS_LOG_DESAFIO"
        FOREIGN KEY ("ID_DESAFIO")
        REFERENCES "DM_VENDAS"."DESAFIOS_COMERCIAIS" ("ID_DESAFIO") ENABLE
)
SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
NOCOMPRESS LOGGING
TABLESPACE "DADOS";

COMMENT ON TABLE "DM_VENDAS"."DESAFIOS_COMERCIAIS_LOG" IS 'Historico dos eventos do desafio.';

CREATE INDEX "DM_VENDAS"."IDX_DESAFIOS_LOG_DESAFIO"
    ON "DM_VENDAS"."DESAFIOS_COMERCIAIS_LOG" ("ID_DESAFIO", "DATA_EVENTO" DESC)
    TABLESPACE "DADOS";


-- -----------------------------------------------------------------------------
-- 4.2 DESAFIOS_COMERCIAIS_METAS
-- Metas internas do desafio. Um desafio pode ter uma ou varias metas.
-- Depende de: DESAFIOS_COMERCIAIS
-- -----------------------------------------------------------------------------
CREATE TABLE "DM_VENDAS"."DESAFIOS_COMERCIAIS_METAS"
(
    "ID_META"          NUMBER(18,0),
    "ID_DESAFIO"       NUMBER(18,0)    NOT NULL ENABLE,
    "TIPO_META"        VARCHAR2(40 CHAR) NOT NULL ENABLE,
    "META_VALOR"       NUMBER(18,2)    NOT NULL ENABLE,
    "UNIDADE_META"     VARCHAR2(40 CHAR),
    "RECOMPENSA_VALOR" NUMBER(18,2)    DEFAULT 0 NOT NULL ENABLE,
    "METRIC_TYPE"      VARCHAR2(20 CHAR) DEFAULT 'VALOR' NOT NULL ENABLE,
    "ORDEM_EXIBICAO"   NUMBER(4,0)     DEFAULT 1 NOT NULL ENABLE,
    "CONFIG_JSON"      CLOB,
    "CRIADO_EM"        DATE            DEFAULT SYSDATE NOT NULL ENABLE,
    "ATUALIZADO_EM"    DATE            DEFAULT SYSDATE NOT NULL ENABLE,
    CONSTRAINT "CK_DESAFIOS_TIPO_META"
        CHECK (tipo_meta IN
            ('FATURAMENTO','PEDIDOS_FECHADOS','CLIENTES_ATENDIDOS',
             'RECUPERAR_CLIENTES','PRODUTO_OU_MARCA')) ENABLE,
    CONSTRAINT "PK_DESAFIOS_COMERCIAIS_METAS" PRIMARY KEY ("ID_META")
        USING INDEX TABLESPACE "DADOS",
    CONSTRAINT "FK_DESAFIOS_META_DESAFIO"
        FOREIGN KEY ("ID_DESAFIO")
        REFERENCES "DM_VENDAS"."DESAFIOS_COMERCIAIS" ("ID_DESAFIO") ENABLE
)
SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
NOCOMPRESS LOGGING
TABLESPACE "DADOS"
LOB ("CONFIG_JSON") STORE AS SECUREFILE (
    TABLESPACE "DADOS" ENABLE STORAGE IN ROW CHUNK 8192
    NOCACHE LOGGING NOCOMPRESS KEEP_DUPLICATES);

COMMENT ON TABLE  "DM_VENDAS"."DESAFIOS_COMERCIAIS_METAS"             IS 'Metas internas do desafio. Um desafio pode ter uma ou varias metas.';
COMMENT ON COLUMN "DM_VENDAS"."DESAFIOS_COMERCIAIS_METAS"."METRIC_TYPE" IS 'Tipo de medicao da meta: VALOR ou QUANTIDADE.';
COMMENT ON COLUMN "DM_VENDAS"."DESAFIOS_COMERCIAIS_METAS"."CONFIG_JSON" IS 'Configuracoes opcionais por meta, como marca, produto, categoria ou modo de medicao.';

CREATE INDEX "DM_VENDAS"."IDX_DESAFIOS_METAS_DESAFIO"
    ON "DM_VENDAS"."DESAFIOS_COMERCIAIS_METAS" ("ID_DESAFIO", "ORDEM_EXIBICAO")
    TABLESPACE "DADOS";


-- -----------------------------------------------------------------------------
-- 4.3 DESAFIOS_COMERCIAIS_VENDEDORES
-- Participacao do vendedor no desafio, incluindo aceite e visualizacao.
-- Depende de: DESAFIOS_COMERCIAIS
-- -----------------------------------------------------------------------------
CREATE TABLE "DM_VENDAS"."DESAFIOS_COMERCIAIS_VENDEDORES"
(
    "ID"                    NUMBER(18,0),
    "ID_DESAFIO"            NUMBER(18,0)    NOT NULL ENABLE,
    "SK_VENDEDOR"           NUMBER(18,0)    NOT NULL ENABLE,
    "NOME_VENDEDOR"         VARCHAR2(160 CHAR),
    "STATUS_PARTICIPACAO"   VARCHAR2(20 CHAR) DEFAULT 'DISPONIVEL' NOT NULL ENABLE,
    "VISUALIZADO_EM"        DATE,
    "ACEITO_EM"             DATE,
    "PREMIO_TOTAL_LIBERADO" NUMBER(18,2)    DEFAULT 0 NOT NULL ENABLE,
    "CONCLUIDO_EM"          DATE,
    "ULTIMA_ATUALIZACAO"    DATE            DEFAULT SYSDATE NOT NULL ENABLE,
    CONSTRAINT "CK_DESAFIOS_STATUS_PARTICIPACAO"
        CHECK (status_participacao IN
            ('CONVIDADO','DISPONIVEL','ACEITO','EM_ANDAMENTO',
             'CONCLUIDO','EXPIRADO','RECUSADO')) ENABLE,
    CONSTRAINT "PK_DESAFIOS_COMERCIAIS_VENDEDORES" PRIMARY KEY ("ID")
        USING INDEX TABLESPACE "DADOS",
    CONSTRAINT "UK_DESAFIO_VENDEDOR"
        UNIQUE ("ID_DESAFIO", "SK_VENDEDOR")
        USING INDEX TABLESPACE "DADOS",
    CONSTRAINT "FK_DESAFIOS_VENDEDOR_DESAFIO"
        FOREIGN KEY ("ID_DESAFIO")
        REFERENCES "DM_VENDAS"."DESAFIOS_COMERCIAIS" ("ID_DESAFIO") ENABLE
)
SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
NOCOMPRESS LOGGING
TABLESPACE "DADOS";

COMMENT ON TABLE "DM_VENDAS"."DESAFIOS_COMERCIAIS_VENDEDORES"
    IS 'Participacao do vendedor no desafio, incluindo aceite e visualizacao.';

CREATE INDEX "DM_VENDAS"."IDX_DESAFIOS_VENDEDORES_LOOKUP"
    ON "DM_VENDAS"."DESAFIOS_COMERCIAIS_VENDEDORES"
        ("SK_VENDEDOR", "STATUS_PARTICIPACAO", "VISUALIZADO_EM")
    TABLESPACE "DADOS";


-- =============================================================================
-- BLOCO 5: TABELAS FILHAS DE DESAFIOS_COMERCIAIS + DESAFIOS_COMERCIAIS_METAS
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 5.1 DESAFIOS_COMERCIAIS_PROGRESSO
-- Progresso por meta e por vendedor.
-- Depende de: DESAFIOS_COMERCIAIS, DESAFIOS_COMERCIAIS_METAS
-- -----------------------------------------------------------------------------
CREATE TABLE "DM_VENDAS"."DESAFIOS_COMERCIAIS_PROGRESSO"
(
    "ID"                   NUMBER(18,0),
    "ID_DESAFIO"           NUMBER(18,0)  NOT NULL ENABLE,
    "ID_META"              NUMBER(18,0)  NOT NULL ENABLE,
    "SK_VENDEDOR"          NUMBER(18,0)  NOT NULL ENABLE,
    "PROGRESSO_ATUAL"      NUMBER(18,2)  DEFAULT 0 NOT NULL ENABLE,
    "PERCENTUAL_CONCLUSAO" NUMBER(7,2)   DEFAULT 0 NOT NULL ENABLE,
    "CONCLUIDO_EM"         DATE,
    "PREMIO_LIBERADO"      CHAR(1 BYTE)  DEFAULT 'N' NOT NULL ENABLE,
    "PREMIO_VALOR"         NUMBER(18,2)  DEFAULT 0 NOT NULL ENABLE,
    "ULTIMA_ATUALIZACAO"   DATE          DEFAULT SYSDATE NOT NULL ENABLE,
    CONSTRAINT "CK_DESAFIOS_PREMIO_LIBERADO"
        CHECK (premio_liberado IN ('S','N')) ENABLE,
    CONSTRAINT "PK_DESAFIOS_COMERCIAIS_PROGRESSO" PRIMARY KEY ("ID")
        USING INDEX TABLESPACE "DADOS",
    CONSTRAINT "UK_DESAFIOS_PROGRESSO"
        UNIQUE ("ID_META", "SK_VENDEDOR")
        USING INDEX TABLESPACE "DADOS",
    CONSTRAINT "FK_DESAFIOS_PROGRESSO_DESAFIO"
        FOREIGN KEY ("ID_DESAFIO")
        REFERENCES "DM_VENDAS"."DESAFIOS_COMERCIAIS" ("ID_DESAFIO") ENABLE,
    CONSTRAINT "FK_DESAFIOS_PROGRESSO_META"
        FOREIGN KEY ("ID_META")
        REFERENCES "DM_VENDAS"."DESAFIOS_COMERCIAIS_METAS" ("ID_META") ENABLE
)
SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
NOCOMPRESS LOGGING
TABLESPACE "DADOS";

COMMENT ON TABLE "DM_VENDAS"."DESAFIOS_COMERCIAIS_PROGRESSO"
    IS 'Progresso por meta e por vendedor.';

CREATE INDEX "DM_VENDAS"."IDX_DESAFIOS_PROGRESSO_LOOKUP"
    ON "DM_VENDAS"."DESAFIOS_COMERCIAIS_PROGRESSO"
        ("ID_DESAFIO", "SK_VENDEDOR", "ID_META")
    TABLESPACE "DADOS";


-- =============================================================================
-- BLOCO 6: TABELAS FILHAS DE FEED_POSTS
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 6.1 FEED_COMENTARIOS
-- Depende de: FEED_POSTS
-- Nota: o trigger usa FEED_COMENTARIOS_SEQ — crie a sequence antes se nao existir.
-- -----------------------------------------------------------------------------
CREATE TABLE "DM_VENDAS"."FEED_COMENTARIOS"
(
    "ID"              NUMBER,
    "POST_ID"         NUMBER          NOT NULL ENABLE,
    "USUARIO_ID"      NUMBER          NOT NULL ENABLE,
    "NOME_USUARIO"    NVARCHAR2(160)  NOT NULL ENABLE,
    "COMENTARIO"      NVARCHAR2(500)  NOT NULL ENABLE,
    "DATA_COMENTARIO" DATE            DEFAULT SYSDATE NOT NULL ENABLE,
    CONSTRAINT "PK_FEED_COMENTARIOS" PRIMARY KEY ("ID")
        USING INDEX TABLESPACE "DADOS",
    CONSTRAINT "FK_FEED_COMENTARIOS_POST"
        FOREIGN KEY ("POST_ID")
        REFERENCES "DM_VENDAS"."FEED_POSTS" ("ID") ON DELETE CASCADE ENABLE
)
SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
NOCOMPRESS LOGGING
TABLESPACE "DADOS";

CREATE INDEX "DM_VENDAS"."IDX_FEED_COMENTARIOS_DATA"
    ON "DM_VENDAS"."FEED_COMENTARIOS" ("DATA_COMENTARIO" DESC) TABLESPACE "DADOS";

CREATE INDEX "DM_VENDAS"."IDX_FEED_COMENTARIOS_POST"
    ON "DM_VENDAS"."FEED_COMENTARIOS" ("POST_ID")              TABLESPACE "DADOS";

CREATE INDEX "DM_VENDAS"."IDX_FEED_COMENTARIOS_USUARIO"
    ON "DM_VENDAS"."FEED_COMENTARIOS" ("USUARIO_ID")           TABLESPACE "DADOS";


-- -----------------------------------------------------------------------------
-- 6.2 FEED_CURTIDAS
-- Depende de: FEED_POSTS
-- Nota: o trigger usa FEED_CURTIDAS_SEQ — crie a sequence antes se nao existir.
-- -----------------------------------------------------------------------------
CREATE TABLE "DM_VENDAS"."FEED_CURTIDAS"
(
    "ID"           NUMBER,
    "POST_ID"      NUMBER  NOT NULL ENABLE,
    "USUARIO_ID"   NUMBER  NOT NULL ENABLE,
    "DATA_CURTIDA" DATE    DEFAULT SYSDATE NOT NULL ENABLE,
    CONSTRAINT "PK_FEED_CURTIDAS" PRIMARY KEY ("ID")
        USING INDEX TABLESPACE "DADOS",
    CONSTRAINT "UQ_FEED_CURTIDAS_POST_USUARIO"
        UNIQUE ("POST_ID", "USUARIO_ID")
        USING INDEX TABLESPACE "DADOS",
    CONSTRAINT "FK_FEED_CURTIDAS_POST"
        FOREIGN KEY ("POST_ID")
        REFERENCES "DM_VENDAS"."FEED_POSTS" ("ID") ON DELETE CASCADE ENABLE
)
SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
NOCOMPRESS LOGGING
TABLESPACE "DADOS";

CREATE INDEX "DM_VENDAS"."IDX_FEED_CURTIDAS_DATA"
    ON "DM_VENDAS"."FEED_CURTIDAS" ("DATA_CURTIDA" DESC) TABLESPACE "DADOS";

CREATE INDEX "DM_VENDAS"."IDX_FEED_CURTIDAS_POST"
    ON "DM_VENDAS"."FEED_CURTIDAS" ("POST_ID")           TABLESPACE "DADOS";

CREATE INDEX "DM_VENDAS"."IDX_FEED_CURTIDAS_USUARIO"
    ON "DM_VENDAS"."FEED_CURTIDAS" ("USUARIO_ID")        TABLESPACE "DADOS";


-- =============================================================================
-- BLOCO 7: TRIGGERS
-- Devem vir apos as tabelas e sequences correspondentes.
-- =============================================================================

CREATE OR REPLACE EDITIONABLE TRIGGER "DM_VENDAS"."TRG_ORGANIZACOES_BI"
BEFORE INSERT ON "DM_VENDAS"."ORGANIZACOES"
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        :NEW.ID := ORGANIZACOES_SEQ.NEXTVAL;
    END IF;
END;
/
ALTER TRIGGER "DM_VENDAS"."TRG_ORGANIZACOES_BI" ENABLE;


CREATE OR REPLACE EDITIONABLE TRIGGER "DM_VENDAS"."TRG_ORGANIZACOES_BU"
BEFORE UPDATE ON "DM_VENDAS"."ORGANIZACOES"
FOR EACH ROW
BEGIN
    :NEW.ATUALIZADO_EM := SYSDATE;
END;
/
ALTER TRIGGER "DM_VENDAS"."TRG_ORGANIZACOES_BU" ENABLE;


CREATE OR REPLACE EDITIONABLE TRIGGER "DM_VENDAS"."TRG_FEED_POSTS_BI"
BEFORE INSERT ON "DM_VENDAS"."FEED_POSTS"
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        :NEW.ID := FEED_POSTS_SEQ.NEXTVAL;
    END IF;
END;
/
ALTER TRIGGER "DM_VENDAS"."TRG_FEED_POSTS_BI" ENABLE;


CREATE OR REPLACE EDITIONABLE TRIGGER "DM_VENDAS"."TRG_FEED_COMENTARIOS_BI"
BEFORE INSERT ON "DM_VENDAS"."FEED_COMENTARIOS"
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        :NEW.ID := FEED_COMENTARIOS_SEQ.NEXTVAL;
    END IF;
END;
/
ALTER TRIGGER "DM_VENDAS"."TRG_FEED_COMENTARIOS_BI" ENABLE;


CREATE OR REPLACE EDITIONABLE TRIGGER "DM_VENDAS"."TRG_FEED_CURTIDAS_BI"
BEFORE INSERT ON "DM_VENDAS"."FEED_CURTIDAS"
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        :NEW.ID := FEED_CURTIDAS_SEQ.NEXTVAL;
    END IF;
END;
/
ALTER TRIGGER "DM_VENDAS"."TRG_FEED_CURTIDAS_BI" ENABLE;


-- =============================================================================
-- BLOCO 8: VIEWS
-- Devem vir por ultimo pois referenciam objetos de outros schemas
-- (FATO_COCKPIT, DIM_VENDEDOR, etc.) que precisam existir antes.
-- =============================================================================

CREATE OR REPLACE FORCE EDITIONABLE VIEW "DM_VENDAS"."VW_RANKING_VENDEDORES"
    ("SK_EMPRESA","SK_VENDEDOR","NOME_VENDEDOR","RECEITA_MES","META_MES",
     "CLIENTES_MES","PERC_ATINGIMENTO","RANKING_ATINGIMENTO","META_HERDADA",
     "VENDEDOR_ID","FUNCIONARIO_ID","CPF_CNPJ_SEM_PONTOS")
AS
WITH mes_referencia AS (
    SELECT
        NVL(
            MAX(CASE WHEN TO_CHAR(dti.DATA,'YYYYMM') = TO_CHAR(SYSDATE,'YYYYMM')
                     THEN TO_CHAR(dti.DATA,'YYYYMM') END),
            MAX(TO_CHAR(dti.DATA,'YYYYMM'))
        ) AS yyyymm_ref
    FROM fato_meta meta
    JOIN dim_data dti ON dti.DATANUM = meta.SK_DATA
),

base_meta AS (
    SELECT
        meta.SK_EMPRESA        AS sk_empresa,
        vendedor.SK_VENDEDOR   AS sk_vendedor,
        vendedor.VENDEDOR_ID   AS vendedor_id,
        vendedor.NOME_VENDEDOR AS nome_vendedor,
        SUM(meta.VL_META)      AS meta_mes
    FROM fato_meta meta
    LEFT JOIN dim_vendedor vendedor ON vendedor.SK_VENDEDOR = meta.SK_VENDEDOR
    LEFT JOIN dim_data dti          ON dti.DATANUM = meta.SK_DATA
    WHERE meta.SK_VENDEDOR <> -1
      AND TO_CHAR(dti.DATA,'YYYYMM') = (SELECT yyyymm_ref FROM mes_referencia)
    GROUP BY meta.SK_EMPRESA, vendedor.SK_VENDEDOR, vendedor.VENDEDOR_ID, vendedor.NOME_VENDEDOR
),

base_vendas AS (
    SELECT
        cockpit.SK_EMPRESA   AS sk_empresa,
        vendedor.SK_VENDEDOR AS sk_vendedor,
        SUM(CASE WHEN tipo_orcamento.TIPO_SINTETICO = 'DEV'
                 THEN cockpit.VALOR_LIQUIDO_ITEM * -1
                 ELSE cockpit.VALOR_LIQUIDO_ITEM END) AS receita_mes,
        COUNT(DISTINCT cockpit.SK_CLIENTE)            AS clientes_mes
    FROM fato_cockpit cockpit
    LEFT JOIN dim_vendedor       vendedor       ON vendedor.SK_VENDEDOR           = cockpit.SK_VENDEDOR
    LEFT JOIN dim_data           dti            ON dti.DATANUM                    = cockpit.SK_DATA
    LEFT JOIN dim_tipo_orcamento tipo_orcamento ON tipo_orcamento.SK_TIPO_ORCAMENTO = cockpit.SK_TIPO_ORCAMENTO
    WHERE cockpit.SK_VENDEDOR <> -1
      AND TO_CHAR(dti.DATA,'YYYYMM') = TO_CHAR(SYSDATE,'YYYYMM')
    GROUP BY cockpit.SK_EMPRESA, vendedor.SK_VENDEDOR
),

funcionario_dados AS (
    SELECT funcionario_id, MAX(CPF_CNPJ_SEM_PONTOS) AS CPF_CNPJ_SEM_PONTOS
    FROM fato_funcionarios_acessos
    GROUP BY funcionario_id
)

SELECT
    m.sk_empresa,
    m.sk_vendedor,
    REGEXP_SUBSTR(
        TRIM(SUBSTR(m.nome_vendedor, 1, INSTR(m.nome_vendedor || '(','(') - 1)),
        '^\S+'
    ) || ' ' ||
    REGEXP_SUBSTR(
        TRIM(SUBSTR(m.nome_vendedor, 1, INSTR(m.nome_vendedor || '(','(') - 1)),
        '\S+$'
    ) AS nome_vendedor,
    TRUNC(NVL(v.receita_mes, 0), 2)  AS receita_mes,
    TRUNC(m.meta_mes, 2)              AS meta_mes,
    NVL(v.clientes_mes, 0)            AS clientes_mes,
    TRUNC(CASE WHEN m.meta_mes > 0
               THEN NVL(v.receita_mes, 0) / m.meta_mes
               ELSE 0 END, 2)         AS perc_atingimento,
    RANK() OVER (
        PARTITION BY m.sk_empresa
        ORDER BY CASE WHEN m.meta_mes > 0
                      THEN NVL(v.receita_mes,0) / m.meta_mes
                      ELSE 0 END DESC
    ) AS ranking_atingimento,
    CASE WHEN TO_CHAR(SYSDATE,'YYYYMM') <> (SELECT yyyymm_ref FROM mes_referencia)
         THEN 1 ELSE 0 END AS meta_herdada,
    m.vendedor_id,
    f.funcionario_id,
    f.CPF_CNPJ_SEM_PONTOS
FROM base_meta m
LEFT JOIN base_vendas     v ON v.sk_empresa  = m.sk_empresa  AND v.sk_vendedor = m.sk_vendedor
LEFT JOIN funcionario_dados f ON f.funcionario_id = m.vendedor_id;


CREATE OR REPLACE FORCE EDITIONABLE VIEW "DM_VENDAS"."VW_RANKING_VENDEDORES_DIA"
    ("DATA_REFERENCIA","SK_EMPRESA","NOME_RESUMIDO","SK_VENDEDOR","NOME_VENDEDOR",
     "RECEITA_DIA","CLIENTES_DIA","TICKET_MEDIO_DIA","META_MES","DIAS_RESTANTES",
     "META_RESTANTE","META_DIARIA_NECESSARIA","STATUS_DIA","PERC_PERFORMANCE_DIA",
     "RANKING_DIA","VENDEDOR_ID","CPF")
AS
WITH params AS (
    SELECT GREATEST(
        (SELECT MAX(dti.DATA) FROM FATO_COCKPIT fc  JOIN DIM_DATA dti ON dti.DATANUM = fc.SK_DATA),
        (SELECT MAX(dti.DATA) FROM FATO_META_DIA fmd JOIN DIM_DATA dti ON dti.DATANUM = fmd.SK_DATA)
    ) AS data_ref
    FROM dual
),

cal AS (
    SELECT p.data_ref,
           TRUNC(p.data_ref, 'MM')       AS ini_mes_ref,
           TO_CHAR(p.data_ref, 'YYYYMM') AS yyyymm_ref
    FROM params p
),

base_dia AS (
    SELECT meta.SK_EMPRESA, meta.SK_VENDEDOR, vendedor.VENDEDOR_ID AS vendedor_id,
           MAX(meta.DIAS_RESTANTES)  AS dias_restantes,
           MAX(meta.VALOR_META_DIA)  AS valor_meta_dia
    FROM FATO_META_DIA meta
    JOIN DIM_DATA dti ON dti.DATANUM = meta.SK_DATA
    LEFT JOIN DIM_VENDEDOR vendedor ON vendedor.SK_VENDEDOR = meta.SK_VENDEDOR
    CROSS JOIN cal c
    WHERE meta.SK_VENDEDOR <> -1
      AND dti.DATA = (
            SELECT MAX(d2.DATA)
            FROM FATO_META_DIA m2
            JOIN DIM_DATA d2 ON d2.DATANUM = m2.SK_DATA
            WHERE m2.SK_EMPRESA  = meta.SK_EMPRESA
              AND m2.SK_VENDEDOR = meta.SK_VENDEDOR
              AND d2.DATA <= c.data_ref)
    GROUP BY meta.SK_EMPRESA, meta.SK_VENDEDOR, vendedor.VENDEDOR_ID
),

vendas_hoje AS (
    SELECT cockpit.SK_EMPRESA, cockpit.SK_VENDEDOR,
           SUM(CASE WHEN tipo_orcamento.TIPO_SINTETICO = 'DEV'
                    THEN cockpit.VALOR_LIQUIDO_ITEM * -1
                    ELSE cockpit.VALOR_LIQUIDO_ITEM END) AS receita_dia,
           COUNT(DISTINCT cockpit.SK_CLIENTE)            AS clientes_dia
    FROM FATO_COCKPIT cockpit
    JOIN DIM_DATA dti ON dti.DATANUM = cockpit.SK_DATA
    LEFT JOIN DIM_TIPO_ORCAMENTO tipo_orcamento
        ON tipo_orcamento.SK_TIPO_ORCAMENTO = cockpit.SK_TIPO_ORCAMENTO
    CROSS JOIN cal c
    WHERE cockpit.SK_VENDEDOR <> -1 AND dti.DATA = c.data_ref
    GROUP BY cockpit.SK_EMPRESA, cockpit.SK_VENDEDOR
),

mes_meta_ref AS (
    SELECT NVL(
        MAX(CASE WHEN TO_CHAR(dti.DATA,'YYYYMM') = TO_CHAR(SYSDATE,'YYYYMM')
                 THEN TO_CHAR(dti.DATA,'YYYYMM') END),
        MAX(TO_CHAR(dti.DATA,'YYYYMM'))
    ) AS yyyymm_meta_ref
    FROM FATO_META meta
    JOIN DIM_DATA dti ON dti.DATANUM = meta.SK_DATA
),

meta_mensal AS (
    SELECT meta.SK_EMPRESA, meta.SK_VENDEDOR, SUM(meta.VL_META) AS meta_mes
    FROM FATO_META meta
    JOIN DIM_DATA dti ON dti.DATANUM = meta.SK_DATA
    WHERE meta.SK_VENDEDOR <> -1
      AND TO_CHAR(dti.DATA,'YYYYMM') = (SELECT yyyymm_meta_ref FROM mes_meta_ref)
    GROUP BY meta.SK_EMPRESA, meta.SK_VENDEDOR
),

receita_mes AS (
    SELECT cockpit.SK_EMPRESA, cockpit.SK_VENDEDOR,
           SUM(CASE WHEN tipo_orcamento.TIPO_SINTETICO = 'DEV'
                    THEN cockpit.VALOR_LIQUIDO_ITEM * -1
                    ELSE cockpit.VALOR_LIQUIDO_ITEM END) AS receita_mes_acumulada
    FROM FATO_COCKPIT cockpit
    JOIN DIM_DATA dti ON dti.DATANUM = cockpit.SK_DATA
    LEFT JOIN DIM_TIPO_ORCAMENTO tipo_orcamento
        ON tipo_orcamento.SK_TIPO_ORCAMENTO = cockpit.SK_TIPO_ORCAMENTO
    CROSS JOIN cal c
    WHERE cockpit.SK_VENDEDOR <> -1
      AND dti.DATA BETWEEN c.ini_mes_ref AND c.data_ref
    GROUP BY cockpit.SK_EMPRESA, cockpit.SK_VENDEDOR
),

funcionario_cpf AS (
    SELECT funcionario_id, MAX(CPF_CNPJ_SEM_PONTOS) AS cpf
    FROM FATO_FUNCIONARIOS_ACESSOS
    GROUP BY funcionario_id
)

SELECT
    c.data_ref AS data_referencia,
    b.SK_EMPRESA AS sk_empresa,
    emp.NOME_RESUMIDO AS nome_resumido,
    b.SK_VENDEDOR AS sk_vendedor,
    REGEXP_SUBSTR(
        TRIM(SUBSTR(vendedor.NOME_VENDEDOR, 1, INSTR(vendedor.NOME_VENDEDOR || '(','(') - 1)),
        '^\S+'
    ) || ' ' ||
    REGEXP_SUBSTR(
        TRIM(SUBSTR(vendedor.NOME_VENDEDOR, 1, INSTR(vendedor.NOME_VENDEDOR || '(','(') - 1)),
        '\S+$'
    ) AS nome_vendedor,
    NVL(v.receita_dia,  0)  AS receita_dia,
    NVL(v.clientes_dia, 0)  AS clientes_dia,
    CASE WHEN NVL(v.clientes_dia,0) > 0
         THEN NVL(v.receita_dia,0) / v.clientes_dia
         ELSE 0 END          AS ticket_medio_dia,
    NVL(m.meta_mes, 0)       AS meta_mes,
    b.dias_restantes,
    (m.meta_mes - NVL(rm.receita_mes_acumulada, 0)) AS meta_restante,
    NVL(b.valor_meta_dia, 0) AS meta_diaria_necessaria,
    CASE WHEN NVL(v.receita_dia, 0) >= NVL(b.valor_meta_dia, 0)
         THEN 'OK' ELSE 'DEVENDO' END AS status_dia,
    CASE WHEN NVL(b.valor_meta_dia, 0) > 0
         THEN NVL(v.receita_dia, 0) / NVL(b.valor_meta_dia, 0)
         ELSE 0 END AS perc_performance_dia,
    RANK() OVER (
        PARTITION BY b.SK_EMPRESA
        ORDER BY NVL(v.receita_dia, 0) DESC
    ) AS ranking_dia,
    b.vendedor_id AS vendedor_id,
    f.cpf         AS cpf
FROM base_dia b
CROSS JOIN cal c
LEFT JOIN DIM_VENDEDOR  vendedor ON vendedor.SK_VENDEDOR = b.SK_VENDEDOR
LEFT JOIN DIM_EMPRESAS  emp      ON emp.SK_EMPRESAS      = b.SK_EMPRESA
LEFT JOIN vendas_hoje   v        ON v.SK_EMPRESA = b.SK_EMPRESA  AND v.SK_VENDEDOR = b.SK_VENDEDOR
LEFT JOIN meta_mensal   m        ON m.SK_EMPRESA = b.SK_EMPRESA  AND m.SK_VENDEDOR = b.SK_VENDEDOR
LEFT JOIN receita_mes   rm       ON rm.SK_EMPRESA = b.SK_EMPRESA AND rm.SK_VENDEDOR = b.SK_VENDEDOR
LEFT JOIN funcionario_cpf f      ON f.funcionario_id = b.vendedor_id
WHERE m.meta_mes IS NOT NULL;


CREATE OR REPLACE FORCE EDITIONABLE VIEW "DM_VENDAS"."VW_RANKING_VENDEDORES_DIA_HIST"
    ("DATA_REF","SK_EMPRESA","SK_VENDEDOR","NOME_VENDEDOR","RECEITA_DIA",
     "META_DIA","SALDO_DIA","RANKING_DIA","RECEITA_MES_ACUM")
AS
WITH vendas_dia AS (
    SELECT c.SK_EMPRESA, c.SK_VENDEDOR, d.DATA AS DATA_REF,
           SUM(CASE WHEN t.TIPO_SINTETICO = 'DEV'
                    THEN c.VALOR_LIQUIDO_ITEM * -1
                    ELSE c.VALOR_LIQUIDO_ITEM END) AS RECEITA_DIA
    FROM FATO_COCKPIT c
    JOIN DIM_DATA d          ON d.DATANUM           = c.SK_DATA
    JOIN DIM_TIPO_ORCAMENTO t ON t.SK_TIPO_ORCAMENTO = c.SK_TIPO_ORCAMENTO
    WHERE c.SK_VENDEDOR <> -1 AND d.DATA >= TRUNC(SYSDATE,'MM')
    GROUP BY c.SK_EMPRESA, c.SK_VENDEDOR, d.DATA
),

meta_dia AS (
    SELECT m.SK_EMPRESA, m.SK_VENDEDOR, d.DATA AS DATA_REF,
           SUM(m.VALOR_META_DIA) AS META_DIA
    FROM FATO_META_DIA m
    JOIN DIM_DATA d ON d.DATANUM = m.SK_DATA
    WHERE m.SK_VENDEDOR <> -1 AND d.DATA >= TRUNC(SYSDATE,'MM')
    GROUP BY m.SK_EMPRESA, m.SK_VENDEDOR, d.DATA
),

base AS (
    SELECT v.SK_EMPRESA, v.SK_VENDEDOR, v.DATA_REF,
           v.RECEITA_DIA,
           NVL(m.META_DIA, 0) AS META_DIA
    FROM vendas_dia v
    LEFT JOIN meta_dia m
        ON  m.SK_EMPRESA  = v.SK_EMPRESA
        AND m.SK_VENDEDOR = v.SK_VENDEDOR
        AND m.DATA_REF    = v.DATA_REF
)

SELECT
    b.DATA_REF,
    b.SK_EMPRESA,
    b.SK_VENDEDOR,
    dv.NOME_VENDEDOR,
    b.RECEITA_DIA,
    b.META_DIA,
    (b.RECEITA_DIA - b.META_DIA) AS SALDO_DIA,
    DENSE_RANK() OVER (
        PARTITION BY b.SK_EMPRESA, b.DATA_REF
        ORDER BY b.RECEITA_DIA DESC
    ) AS RANKING_DIA,
    SUM(b.RECEITA_DIA) OVER (
        PARTITION BY b.SK_EMPRESA, b.SK_VENDEDOR, TRUNC(b.DATA_REF,'MM')
        ORDER BY b.DATA_REF
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS RECEITA_MES_ACUM
FROM base b
LEFT JOIN DIM_VENDEDOR dv ON dv.SK_VENDEDOR = b.SK_VENDEDOR;


CREATE OR REPLACE FORCE EDITIONABLE VIEW "DM_VENDAS"."VW_ORCAMENTOS_GESTAO_METAS"
    ("VENDEDOR_ID","VENDEDOR","DATA","ID","CLIENTE","VALOR",
     "DESCRICAO_STATUS","AGRUPAMENTO","TELEFONE")
AS
SELECT
    ven.vendedor_id                           AS VENDEDOR_ID,
    ven.nome_vendedor                         AS VENDEDOR,
    TO_CHAR(orc.data_cadastro,'DD/MM/YY')     AS DATA,
    orc.orcamento_id                          AS ID,
    cli.nome_cliente                          AS CLIENTE,
    orc.valor_pedido                          AS VALOR,
    CASE
        WHEN orc.STATUS = 'ORC' THEN 'Sem acompanhamento'
        WHEN orc.STATUS = 'VEN' THEN 'Venda Fechada'
        WHEN orc.STATUS = 'REC' THEN 'Recebida'
        WHEN orc.STATUS = 'CNE' THEN 'Cliente nao encontrado'
        WHEN orc.STATUS = 'CNC' THEN 'Combinado novo contato'
        WHEN orc.STATUS = 'SRC' THEN 'Sem retorno de contato combinado'
        WHEN orc.STATUS = 'DVT' THEN 'Desistiu da venda temporariamente'
        WHEN orc.STATUS = 'DVD' THEN 'Desistiu da venda definitivamente'
        WHEN orc.STATUS = 'CCO' THEN 'Comprou no concorrente'
        WHEN orc.STATUS = 'OEX' THEN 'Excluido do ADM'
        WHEN orc.STATUS = 'ORE' THEN 'Rejeito pelo cadastro'
        WHEN orc.STATUS = 'FOV' THEN 'Fechado por outro vendedor'
        WHEN orc.STATUS = 'FOO' THEN 'Fechando em outro orcamento'
        WHEN orc.STATUS = 'FPR' THEN 'Falta de produto'
        WHEN orc.STATUS = 'EIM' THEN 'Entrega impossibilitada'
        WHEN orc.STATUS = 'EDC' THEN 'Exportacao de dados em contingencia'
        WHEN orc.STATUS = 'ENE' THEN 'Em Negociacao'
        ELSE 'Status Desconhecido'
    END AS DESCRICAO_STATUS,
    CASE
        WHEN orc.STATUS IN ('ORC','CNC','DVT','ENE') THEN 'Possiveis Vendas'
        ELSE 'Possiveis Perdas'
    END AS AGRUPAMENTO,
    NVL(tel.telefone,'Sem telefone cadastrado') AS TELEFONE
FROM fato_orcamento orc
LEFT JOIN dim_empresas emp ON emp.empresa_id = orc.empresa_id
LEFT JOIN dim_vendedor ven ON ven.vendedor_id       = orc.vendedor_id
                          AND ven.empresa_venda_id  = emp.empresa_id
LEFT JOIN dim_cliente  cli ON cli.cadastro_id = orc.cadastro_id
LEFT JOIN (
    SELECT cadastro_id, telefone
    FROM (
        SELECT
            cadastro_id, telefone,
            ROW_NUMBER() OVER (
                PARTITION BY cadastro_id
                ORDER BY
                    CASE WHEN SUBSTR(REGEXP_REPLACE(telefone,'[^0-9]'), 3, 1) = '9'
                         THEN 1 ELSE 2 END,
                    telefone
            ) AS rn
        FROM dim_telefone
    )
    WHERE rn = 1
) tel ON tel.cadastro_id = orc.cadastro_id;


-- =============================================================================
-- FIM DO SCRIPT
-- =============================================================================
