ALTER TABLE FEED_POSTS ADD (
  VISIBILIDADE VARCHAR2(20) DEFAULT 'PUBLICO' NOT NULL,
  DESTINATARIO_USUARIO_ID NUMBER NULL,
  DESTINATARIO_NOME NVARCHAR2(255) NULL,
  DESTINATARIO_TIPO VARCHAR2(30) NULL
);

CREATE INDEX IDX_FEED_POSTS_VISIBILIDADE
ON FEED_POSTS (
  EMPRESA_ID,
  VISIBILIDADE,
  DESTINATARIO_USUARIO_ID
);

CREATE INDEX IDX_FEED_POSTS_AUTOR_DEST
ON FEED_POSTS (
  EMPRESA_ID,
  USUARIO_ID,
  DESTINATARIO_USUARIO_ID
);
