CREATE TABLE GM_TB_FORNECEDORES_LOGIN (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR2(160 CHAR) NOT NULL,
  codigo VARCHAR2(60 CHAR) NOT NULL,
  senha_hash VARCHAR2(255 CHAR) NOT NULL,
  marca VARCHAR2(120 CHAR) NOT NULL,
  ativo CHAR(1) DEFAULT 'S' NOT NULL,
  criado_em DATE DEFAULT SYSDATE NOT NULL,
  atualizado_em DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT uk_fornecedores_login_codigo UNIQUE (codigo),
  CONSTRAINT ck_fornecedores_login_ativo CHECK (ativo IN ('S', 'N'))
);

CREATE INDEX idx_fornecedores_login_marca
  ON GM_TB_FORNECEDORES_LOGIN (marca, ativo);

COMMENT ON TABLE GM_TB_FORNECEDORES_LOGIN IS 'Credenciais de acesso para parceiros da industria.';
COMMENT ON COLUMN GM_TB_FORNECEDORES_LOGIN.codigo IS 'Codigo de login do parceiro, por exemplo SUVINIL01.';
COMMENT ON COLUMN GM_TB_FORNECEDORES_LOGIN.senha_hash IS 'Senha protegida com bcrypt.';
COMMENT ON COLUMN GM_TB_FORNECEDORES_LOGIN.marca IS 'Marca usada para filtrar os dados do portal.';

/*
Exemplo de carga:

INSERT INTO GM_TB_FORNECEDORES_LOGIN (nome, codigo, senha_hash, marca, ativo)
VALUES (
  'Suvinil',
  'SUVINIL01',
  '$2b$10$substitua_por_um_hash_bcrypt_real',
  'SUVINIL',
  'S'
);
*/
