-- Escada de faixas do acelerador de margem+frete (Fase 1 do Plano Tecnico de Melhorias para
-- Vendedores - Simulador de margem/premiacao). Executar como DM_VENDAS (mesmo schema das
-- demais tabelas de parametro da premiacao, ver PARAM_PERCENTUAL_GRUPO_PREMIACAO).
--
-- Ate esta migracao, a escada completa (todos os limites de margem+frete e o % de cada faixa)
-- so existia dentro da logica da view VW_PREMIACAO_VENDEDOR_COMISSAO_ERP /
-- VW_APURACAO_PREMIACAO_VENDEDOR, sem tabela consultavel - o app so via a faixa atual do
-- vendedor (uma linha da view) e inferia o limite superior dela por regex
-- (extrairLimiteSuperiorFaixa em premiacaoVendedorService.js). Esta tabela nao substitui a
-- view (que continua sendo a fonte oficial da faixa/acelerador do mes corrente): ela existe
-- para o simulador conseguir recalcular "se eu vender mais R$X, para qual faixa eu vou".
--
-- Mesmo padrao de vigencia de PARAM_PERCENTUAL_GRUPO_PREMIACAO: nunca dar UPDATE em linha
-- vigente. Para trocar a escada inteira, fechar a vigencia de TODAS as linhas vigentes
-- (DT_FIM_VIGENCIA = dia anterior a edicao) e inserir a nova leva completa de linhas com
-- DT_INICIO_VIGENCIA = data da edicao e DT_FIM_VIGENCIA = NULL (ver
-- premiacaoSimuladorService.js -> salvarFaixasAcelerador).

CREATE TABLE PARAM_FAIXA_ACELERADOR_PREMIACAO (
    ID                     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    LIMITE_INFERIOR        NUMBER(14,2)       NOT NULL,
    LIMITE_SUPERIOR        NUMBER(14,2),
    PERC_ACELERADOR        NUMBER(6,4)        NOT NULL,
    BONUS_FIXO_ADICIONAL   NUMBER(14,2)       DEFAULT 0 NOT NULL,
    DT_INICIO_VIGENCIA     DATE               NOT NULL,
    DT_FIM_VIGENCIA        DATE,
    CRIADO_POR_USUARIO_ID  NUMBER             NOT NULL,
    CRIADO_EM              TIMESTAMP          DEFAULT SYSTIMESTAMP,
    CONSTRAINT CK_FAIXA_ACEL_LIMITES CHECK (LIMITE_SUPERIOR IS NULL OR LIMITE_SUPERIOR > LIMITE_INFERIOR),
    CONSTRAINT UQ_FAIXA_ACEL_VIGENCIA UNIQUE (LIMITE_INFERIOR, DT_INICIO_VIGENCIA)
);

CREATE INDEX IDX_PARAM_FAIXA_ACEL_VIGENTE
    ON PARAM_FAIXA_ACELERADOR_PREMIACAO (DT_FIM_VIGENCIA, LIMITE_INFERIOR);

COMMENT ON TABLE  PARAM_FAIXA_ACELERADOR_PREMIACAO                       IS 'Escada completa de faixas do acelerador de margem+frete (limites, % e bonus fixo por faixa), com historico de vigencias. Alimenta o simulador de premiacao (Fase 1); a apuracao oficial do mes corrente continua vindo de VW_PREMIACAO_VENDEDOR_COMISSAO_ERP.';
COMMENT ON COLUMN PARAM_FAIXA_ACELERADOR_PREMIACAO.LIMITE_INFERIOR       IS 'Limite inferior (exclusive, exceto na primeira faixa) de margem+frete da faixa, em R$.';
COMMENT ON COLUMN PARAM_FAIXA_ACELERADOR_PREMIACAO.LIMITE_SUPERIOR       IS 'Limite superior (inclusive) de margem+frete da faixa, em R$. NULL na ultima faixa (sem teto).';
COMMENT ON COLUMN PARAM_FAIXA_ACELERADOR_PREMIACAO.PERC_ACELERADOR       IS 'Multiplicador direto do acelerador (ex.: 0.5 = 50%, 2 = 200%) - mesma convencao de VW_PREMIACAO_VENDEDOR_COMISSAO_ERP.PERC_ACELERADOR.';
COMMENT ON COLUMN PARAM_FAIXA_ACELERADOR_PREMIACAO.BONUS_FIXO_ADICIONAL  IS 'Bonus fixo adicional (em R$) somado a premiacao final do vendedor que atingir esta faixa.';
COMMENT ON COLUMN PARAM_FAIXA_ACELERADOR_PREMIACAO.DT_FIM_VIGENCIA       IS 'NULL enquanto a linha estiver vigente.';
COMMENT ON COLUMN PARAM_FAIXA_ACELERADOR_PREMIACAO.CRIADO_POR_USUARIO_ID IS 'Usuario (gerente) que cadastrou esta vigencia da escada.';

-- Seed inicial com a escada real informada pelo negocio em 2026-09-24 (Guilherme Diniz).
-- Ajustar CRIADO_POR_USUARIO_ID para um usuario gerente valido do tenant antes de rodar.
DECLARE
  v_data_edicao DATE := TRUNC(SYSDATE);
  v_usuario_id  NUMBER := 1; -- TODO: ajustar para o usuario gerente que esta rodando a migracao
BEGIN
  INSERT INTO PARAM_FAIXA_ACELERADOR_PREMIACAO
    (LIMITE_INFERIOR, LIMITE_SUPERIOR, PERC_ACELERADOR, BONUS_FIXO_ADICIONAL, DT_INICIO_VIGENCIA, DT_FIM_VIGENCIA, CRIADO_POR_USUARIO_ID)
  VALUES (0,      20000,  0,   0,    v_data_edicao, NULL, v_usuario_id);
  INSERT INTO PARAM_FAIXA_ACELERADOR_PREMIACAO
    (LIMITE_INFERIOR, LIMITE_SUPERIOR, PERC_ACELERADOR, BONUS_FIXO_ADICIONAL, DT_INICIO_VIGENCIA, DT_FIM_VIGENCIA, CRIADO_POR_USUARIO_ID)
  VALUES (20000,  30000,  0.5, 0,    v_data_edicao, NULL, v_usuario_id);
  INSERT INTO PARAM_FAIXA_ACELERADOR_PREMIACAO
    (LIMITE_INFERIOR, LIMITE_SUPERIOR, PERC_ACELERADOR, BONUS_FIXO_ADICIONAL, DT_INICIO_VIGENCIA, DT_FIM_VIGENCIA, CRIADO_POR_USUARIO_ID)
  VALUES (30000,  40000,  1,   0,    v_data_edicao, NULL, v_usuario_id);
  INSERT INTO PARAM_FAIXA_ACELERADOR_PREMIACAO
    (LIMITE_INFERIOR, LIMITE_SUPERIOR, PERC_ACELERADOR, BONUS_FIXO_ADICIONAL, DT_INICIO_VIGENCIA, DT_FIM_VIGENCIA, CRIADO_POR_USUARIO_ID)
  VALUES (40000,  50000,  1.5, 0,    v_data_edicao, NULL, v_usuario_id);
  INSERT INTO PARAM_FAIXA_ACELERADOR_PREMIACAO
    (LIMITE_INFERIOR, LIMITE_SUPERIOR, PERC_ACELERADOR, BONUS_FIXO_ADICIONAL, DT_INICIO_VIGENCIA, DT_FIM_VIGENCIA, CRIADO_POR_USUARIO_ID)
  VALUES (50000,  60000,  2,   0,    v_data_edicao, NULL, v_usuario_id);
  INSERT INTO PARAM_FAIXA_ACELERADOR_PREMIACAO
    (LIMITE_INFERIOR, LIMITE_SUPERIOR, PERC_ACELERADOR, BONUS_FIXO_ADICIONAL, DT_INICIO_VIGENCIA, DT_FIM_VIGENCIA, CRIADO_POR_USUARIO_ID)
  VALUES (60000,  70000,  2,   500,  v_data_edicao, NULL, v_usuario_id);
  INSERT INTO PARAM_FAIXA_ACELERADOR_PREMIACAO
    (LIMITE_INFERIOR, LIMITE_SUPERIOR, PERC_ACELERADOR, BONUS_FIXO_ADICIONAL, DT_INICIO_VIGENCIA, DT_FIM_VIGENCIA, CRIADO_POR_USUARIO_ID)
  VALUES (70000,  80000,  2,   1000, v_data_edicao, NULL, v_usuario_id);
  INSERT INTO PARAM_FAIXA_ACELERADOR_PREMIACAO
    (LIMITE_INFERIOR, LIMITE_SUPERIOR, PERC_ACELERADOR, BONUS_FIXO_ADICIONAL, DT_INICIO_VIGENCIA, DT_FIM_VIGENCIA, CRIADO_POR_USUARIO_ID)
  VALUES (80000,  90000,  2,   1500, v_data_edicao, NULL, v_usuario_id);
  INSERT INTO PARAM_FAIXA_ACELERADOR_PREMIACAO
    (LIMITE_INFERIOR, LIMITE_SUPERIOR, PERC_ACELERADOR, BONUS_FIXO_ADICIONAL, DT_INICIO_VIGENCIA, DT_FIM_VIGENCIA, CRIADO_POR_USUARIO_ID)
  VALUES (90000,  100000, 2,   2000, v_data_edicao, NULL, v_usuario_id);
  INSERT INTO PARAM_FAIXA_ACELERADOR_PREMIACAO
    (LIMITE_INFERIOR, LIMITE_SUPERIOR, PERC_ACELERADOR, BONUS_FIXO_ADICIONAL, DT_INICIO_VIGENCIA, DT_FIM_VIGENCIA, CRIADO_POR_USUARIO_ID)
  VALUES (100000, 110000, 2,   2500, v_data_edicao, NULL, v_usuario_id);
  INSERT INTO PARAM_FAIXA_ACELERADOR_PREMIACAO
    (LIMITE_INFERIOR, LIMITE_SUPERIOR, PERC_ACELERADOR, BONUS_FIXO_ADICIONAL, DT_INICIO_VIGENCIA, DT_FIM_VIGENCIA, CRIADO_POR_USUARIO_ID)
  VALUES (110000, 120000, 2,   3500, v_data_edicao, NULL, v_usuario_id);
  INSERT INTO PARAM_FAIXA_ACELERADOR_PREMIACAO
    (LIMITE_INFERIOR, LIMITE_SUPERIOR, PERC_ACELERADOR, BONUS_FIXO_ADICIONAL, DT_INICIO_VIGENCIA, DT_FIM_VIGENCIA, CRIADO_POR_USUARIO_ID)
  VALUES (120000, 130000, 2,   4000, v_data_edicao, NULL, v_usuario_id);
  -- Ultima faixa: sem teto (LIMITE_SUPERIOR NULL), bonus fixo trava em R$4.000,00 dali pra cima
  -- (confirmado com o negocio: nao aumenta mais alem de R$130.000,01).
  INSERT INTO PARAM_FAIXA_ACELERADOR_PREMIACAO
    (LIMITE_INFERIOR, LIMITE_SUPERIOR, PERC_ACELERADOR, BONUS_FIXO_ADICIONAL, DT_INICIO_VIGENCIA, DT_FIM_VIGENCIA, CRIADO_POR_USUARIO_ID)
  VALUES (130000, NULL,   2,   4000, v_data_edicao, NULL, v_usuario_id);

  COMMIT;
END;
/
